# This is a basic workflow to help you get started with Actions

name: Notify to discord

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  issues:
    types: [created,pinned]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Discord Message Notify
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        args: ${{ github.event.issue.user.login }}さんが「${{ github.event.issue.title }}」を投稿しました。聞きたい/喋りたい人はリアクションお願いします！ ${{ github.event.issue.html_url }}
